using UnityEngine;

public class ParallaxLayer : MonoBehaviour
{
    private float startPos, length;
    public Transform cam;
    public float parallaxEffect;

    void Start()
    {
        startPos = transform.position.x;
        length = GetComponent<SpriteRenderer>().bounds.size.x;
    }

    void LateUpdate()
    {
        float distance = cam.position.x * parallaxEffect;
        float movement = cam.position.x * (1 - parallaxEffect);

        transform.position = new Vector3(
            startPos + distance,
            transform.position.y,
            transform.position.z
        );

        if (movement > startPos + length)
        {
            startPos += length;
        }
        else if (movement < startPos - length)
        {
            startPos -= length;
        }
    }
}
